# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-09 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album_collec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('album_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='album_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('pic_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='music_collec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('music_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='music_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('pic_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='playlist_collec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('playlist_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='playlist_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('pic_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('loginname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
